### ISSUE TITLE
Windows Defender False Positive

### ISSUE THREAD

**Issue by LesFerch** [PaaaulZ/InternetExplorerLauncher#1]
Windows Defender falsely detects your Exe as a virus. It's probably because of the use of an HTA as a means to launch IE. A simpler method, which won't trip Defender, is to open IE via COM. See [my repo](https://github.com/LesFerch/LaunchIE).

**Comment by PaaaulZ** [comment]
Yeah my method is a disaster, triggers Windows SmartScreen too but worked for me as a temporary workaround.
I will add a link to your repo in mine if you don't mind, I would like to use this repo as a collection of methods

**Comment by LesFerch** [comment]
Smartscreen is unavoidable. My exes are signed, but Smartscreen still comes up.

No problem linking to my repo.
